- hosts: localhost

  tasks:
    - name: Run Terraform
      community.general.terraform:
      #cloud.terraform.terraform:
        project_path: 'terraform/'
        state: present
        force_init: yes

    - name: Update inventory
      ansible.builtin.meta: refresh_inventory
